version: "3"

services:
  app:
    image: edukandalski/node:16
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    image: edukandalski/nginx
    build:
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s /docker-entrypoint.sh nginx -g "daemon off;"
    tty: true
    networks:
      - node-network
    depends_on:
      - app
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
